# Generated by Django 4.2.7 on 2025-12-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_support_phone_to_gamesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this fake user can be selected for games')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fake_users',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='allow_system_account',
            field=models.BooleanField(default=False, help_text='Enable fake system accounts to join games'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='free_play',
            field=models.BooleanField(default=False, help_text='Allow real users to win even when fake accounts are active (only available if allow_system_account is on)'),
        ),
        migrations.CreateModel(
            name='FakeUserGameCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('card_layout', models.JSONField(default=dict)),
                ('selected_numbers', models.JSONField(default=list)),
                ('is_winner', models.BooleanField(default=False)),
                ('winning_pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fake_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_cards', to='api.fakeuser')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_cards', to='api.game')),
            ],
            options={
                'db_table': 'fake_user_game_cards',
                'indexes': [models.Index(fields=['game', 'fake_user'], name='fake_user_g_game_id_f432d2_idx'), models.Index(fields=['game', 'card_number'], name='fake_user_g_game_id_ac0634_idx')],
                'unique_together': {('game', 'fake_user')},
            },
        ),
    ]

