# Generated by Django 4.2.7 on 2025-12-20 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_gamesettings_winning_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_reward_given',
            field=models.BooleanField(default=False, help_text='Whether referral reward was already given for this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='User who referred this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
