# Generated by Django 4.2.7 on 2025-12-20 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_referral_reward_given_user_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_reward_given',
            field=models.BooleanField(default=False, help_text="Whether referral reward was already given for THIS user's registration (prevents duplicate rewards if user re-registers)"),
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('amount_added', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcast_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastMessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('message_id', models.IntegerField(help_text='Telegram message ID for deletion')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='api.broadcastmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_messages_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcast_message_recipients',
                'indexes': [models.Index(fields=['broadcast', 'deleted'], name='broadcast_m_broadca_5099fb_idx'), models.Index(fields=['telegram_id', 'message_id'], name='broadcast_m_telegra_505e4a_idx')],
                'unique_together': {('broadcast', 'user')},
            },
        ),
    ]
