# Generated by Django 4.2.7 on 2025-12-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_referral_reward_given_broadcastmessage_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_id'], name='user_telegram_id_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['referred_by'], name='user_referred_by_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='user_created_at_idx'),
        ),
    ]
