# Generated by Django 4.2.7 on 2026-07-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_gamesettings_allow_system_account_and_more'),
        ('api', '0017_faileddepositrequest_and_more'),
        ('api', '0038_bet_split_and_card_unselect_refund'),
    ]

    operations = [
    ]
